name: deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: checkout
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'
          cache: gradle

      - name: build with gradle
        run: |
          cd ./github
          chmod +x ./gradlew 
          ./gradlew build

      - name: login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_ID }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: build and push image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./github/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_ID }}/github:${{ github.sha }}, ${{ secrets.DOCKERHUB_ID }}/github:latest
          build-args: |
            DB_URL=${{ secrets.DB_ENDPOINT }}
          
      - name: deploy image
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST_DEPLOYER }}
          username: ${{ secrets.HOST_DEPLOYER_USERNAME }}
          key: ${{ secrets.SSH_DEPLOYER }}
          port: 22
          script: |
            kubectl set image deployment/github-deployment github=${{ secrets.DOCKERHUB_ID }}/github:${{ github.sha }}
            kubectl rollout restart deployment/github-deployment
